version: "3.1"
services:
    mysql:
        image: mysql:5.7
        command: "--innodb_use_native_aio=0 --character-set-server=utf8 --collation-server=utf8_general_ci"
        container_name: app-mysql
        working_dir: /application
        volumes:
            - ./test_api:/application
            - ./db-storage:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test_api
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        ports:
            - "8806:3306"
    nginx:
        image: nginx:alpine
        container_name: app-nginx
        working_dir: /application
        volumes:
            - ./test_api:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        ports:
            - "8800:80"
    php-fpm:
        build: phpdocker/php-fpm
        container_name: app-php-fpm
        working_dir: /application
        volumes:
            - ./test_api:/application
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini